module.exports = {
  APILOCALURL: "https://localhost:5000/api/",
  APIPRODUCTIONURL:"https://hydroidgas.azurewebsites.net/api/",
  APIACTIVATEURL: "https://hydroidgas.azurewebsites.net/api/",
  

  GETALLROLES: "Roles",
  CREATEROLE: "Roles",
  UPDATEROLE: "Roles",
  DELETEROLE: "Roles",
  GETROLEBYID: "Roles/GetById",

  GETALLUSERS: "Users/GetAll",
  GETCUSTOMERS: "Users/GetCustomers",
  GETALLCUSTOMERS: "Users/GetAllCustomers",
  GETADMINS: "Users/GetAdmin",
  CREATEUSER: "Users/user-register",
  LOGINUSER: "Home/Login",
  CHANGEPASSWORD: "Users/ChangePassword",
  GETUSERBYID: "Users/GetById",
  DELETEUSER: "Users",
  USERSTATUS: "Users/Status",
  USERPROFILE: "Users/Profile",
  RESETPASSWORDS: "Users/ResetPassword",

  GETALLDEVICES: "Device/GetAll",
  GETDEVICES: "Device",
  CREATEDEVICE: "Device",
  UPDATEDEVICE: "Device",
  DELETEDEVICE: "Device",
  GETDEVICEBYID: "Device/GetById",
  GETACTIVEDEVICE: "Device/GetActive",
  GETUSERACTIVEDEVICE: "Device/GetUserActive",
  GETDEVICEBYUSER: "Device/GetByUser",
  UPDATEVALVE: "device/UpdateValveStatus",
  GETDEVICEBALANCE: "device/GetBalance",

  GETALLTICKETS: "Ticket",
  CREATETICKET: "Ticket",
  UPDATETICKET: "Ticket",
  DELETETICKET: "Ticket",
  GETTICKETBYID: "Ticket/GetById",
  GETTICKETBYCATEGORY: "Ticket/GetByCategory",
  GETTICKETBYUSER: "Ticket/GetByUser",
  GETTICKETBYSTATUS: "Ticket/GetByStatus",
  GETTICKETIMAGES: "Ticket/GetTicketImages",

  GETALLTICKETCATEGORIES: "TicketCategory",

  GETALLTICKETRESPONSES: "TicketResponse",
  CREATETICKETRESPONSE: "TicketResponse",
  UPDATEDTICKETRESPONSE: "TicketResponse",
  DELETETICKETRESPONSE: "TicketResponse",
  GETTICKETRESPONSEBYID: "TicketResponse/GetByTicketId",

  GETALLMESSAGES: "Message",
  CREATEMESSAGE: "Message",
  UPDATEMESSAGE: "Message",
  DELETEMESSAGE: "Message",
  GETMESSAGEBYID: "Message/GetById",
  GETDISPLAYMESSAGE: "Message/GetDisplayMessage",

  GETALLNOTIFICATIONS: "Notification",
  CREATENOTIFICATION: "Notification",
  UPDATENOTIFICATION: "Notification",
  DELETENOTIFICATION: "Notification",
  GETNOTIFICATIONBYID: "Notification",
  GETNOTIFICATIONUNREAD: "Notification/unread",
  GETNOTIFICATIONREAD: "Notification/read",
  GETNOTIFICATIONBYDEVICE: "Notification/GetByDevice",

  GETAllNEWS: "News/GetAll",
  GETNEWS: "News",
  CREATENEWS: "News",
  UPDATENEWS: "News",
  DELETENEWS: "News",

  GETALLGASPRICES: "GasPrice/GetAll",
  GETGASPRICES: "GasPrice/",
  CREATEGASPRICE: "GasPrice",
  UPDATEGASPRICE: "GasPrice",
  DELETEGASPRICE: "GasPrice",
  GETGASPRICEPERKG: "GasPrice/GetPricePerKg",
  GETGASBALANCE: "GasPrice/GetUserGasBalance",
  GETCONSUMPTIONSINCELASTRECHARGE: "GasPrice/GetConsumptionSinceLastRecharge",
  GETTODAYCONSUMPTION: "GasPrice/GetTodayConsumption",

  GETRECHARGE: "Recharge",
  CREATERECHARGE: "Recharge",
  UPDATERECHARGE: "Recharge/UpdateStatus",
  DELETERECHARGE: "Recharge",
  UPDATEPAYMENTSTATUS: "Recharge/UpdatePaymentStatus",
  GETUSERRECHARGEBYID: "Recharge/GetByUserId",

  GETALLDISTRIBUTERS: "Distributer/GetAll",
  GETDISTRIBUTER: "Distributer",
  GETDISTRIBUTERBYUSER: "Distributer/GetByUser",
  CREATEDISTRIBUTER: "Distributer",
  UPDATEDISTRIBUTER: "Distributer",
  DELETEDISTRIBUTER: "Distributer",

  PAYMENTORDERREQUEST: "Payments/Process",
};
